### PR TITLE
Update A-Frame to pre-0.9 to work in Oculus Browser

### PR DESCRIPTION
**Pull request by Artyom17**
Oculus Browser requires the latest A-Frame + latest webvr-polyfill for this experience to work. Updating aframe to the latest master (i.e. pre-0.9.0). Note, TWEEN is deprecated and removed there, so that is why re-introducing it separately as a module. Tested on Oculus Quest + Oculus Browser and Oculus Rift + Chrome.

### CODE REVIEW

**Comment by cutec-chris** [comment]
Does anyone review this ? Not that the Quest is out, it world be nice when a-painter work on it...

**Comment by Steveorevo** [comment]
I too would love to see quest compatibility. Millions of units have come online. VR becomng more mainstream than ever.

**Comment by cutec-chris** [comment]
Any news on this ? Sometimes i get the idea, that a-frame is mostly dead.

**Comment by markd315** [comment]
Tested this today on my Quest: works great.

Pretty stale but if anyone sees this I support merging it.

**Comment by inventadero** [comment]
Hi! 
It works fine on Quest (not all the brushes). . .

Bu**t Can't save the A-paint  :/**

**Comment by kalix123** [comment]
Can someone merge this? I really want to play a-painter on my quest.

**Comment by novali51** [comment]
Like inventadero, a-painter works in firefox reality on the Quest 2 BUT impossible d'enregistrer :/ (il faut aussi utiliser la version Desktop...) dev and programmers Go Go GO please ...

**Comment by dmarcos** [comment]
Thanks for the patience. Closing in favor of https://github.com/aframevr/a-painter/pull/261 that bumps A-Painter to A-Frame 1.3.0. It will soon work on Quest 🥳

**Pull request closed without merging**
