### PR TITLE
Fix hotkeys misfire

### PR DESCRIPTION
**Pull request by mrfrase3**
Accidentally cleared my painting when I went to copy the save URL by using ctrl + c 
:/

### CODE REVIEW

**Comment by ngokevin** [comment]
We should remove that hotkey altogether. It was for debugging before the UI was made.

**Comment by mrfrase3** [comment]
It doesn't hurt that they are there and they are handy, I find that I use it fair bit.

**Comment by ngokevin** [comment]
Seemed to hurt when people delete their paintings

**Comment by fernandojsg** [comment]
Good catch, I also use this key when testing models and so on, I'd just leave it for now too.
I find it hard to be doing some cool painting and being in front of the computer so most of the accidental strokes should be when developing and writing on the console or so I guess.

**Pull request merged**
