### PR TITLE
added alternative to git+npm

### PR DESCRIPTION
**Pull request by feiss**

### CODE REVIEW

**Comment by fernandojsg** [comment]
I don't think it's a good idea to list the alternatives to git+npm as it could grow exponentially, and also using as an example a non-opensource solution instead of something simpler like live-server or simplehttpserver from python. 
It's something inherent to any static webapp out there so I believe people could find good resources outside from the repo so we don't need to care about maintaining them along with the "official" supported way.

**Comment by cvan** [comment]
I think this is a good idea, à la

* https://aframe.io/docs/0.4.0/introduction/getting-started.html#grab-the-boilerplate (see aframevr/aframe-site#355)
* https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally

**Comment by fernandojsg** [comment]
Both examples are more like extra information stored in the docs or wiki and they are related to frameworks that you may want to include in your projects and test things. 
Here we have an standalone application and if you want to modify something from the code you need webpack or similar to generate the build again.
It's hard to differentiate how much info add to this kind of repo, for example, should we add also information about CORS in case the user wants to include external images? I believe this info it's general webdev tutorials and we shouldn't duplicate in every repo we have

**Comment by cvan** [comment]
Certainly, I hear you! Easing developer fiction can result in pleasant user-onboarding for newcomers, even if that means repeating redundant information - which could be in the form of a simple external link even.

**Pull request closed without merging**
