### PR TITLE
Use latest aframe master

### PR DESCRIPTION
**Pull request by machenmusik**
per discussion on #159

### CODE REVIEW

**Comment by fernandojsg** [comment]
Cool! I'll give it a try later when I'll arrive home. Could you squash the commits? Thanks!

**Comment by machenmusik** [comment]
yesterday @dmarcos said github does that for you, ran into rebase/squash issues yesterday doing touch support for 0.4.0... but I think squash only will probably be ok.

**Comment by machenmusik** [comment]
(@fernandojsg squashed for you.)

**Comment by fernandojsg** [comment]
@machenmusik I've just tried this PR and the controllers doesn't move, which aframe.min.js are you using? the current 0.4.0 dist?

**Comment by machenmusik** [comment]
it occurs to me that although I split the original Touch support into 3, I didn't test that this worked independently.  Now that we have the official 0.4.0 build, let me quickly check and redo.  May need to merge this back together with the Oculus Touch support PR...

**Comment by machenmusik** [comment]
running into merge issues now.  if you already updated master to 0.4.0, you may only need https://github.com/aframevr/a-painter/pull/163/commits/3967487b21b498176289ac94e2b1f123ab92b1e8

**Comment by machenmusik** [comment]
ok redone and tested on Vive

**Comment by fernandojsg** [comment]
@machenmusik cool! it's working, thanks for the work here :+1:

**Pull request merged**
