### PR TITLE
Support oculus touch

### PR DESCRIPTION
**Pull request by machenmusik**
per discussion on #159; works with #163

### CODE REVIEW

**Comment by machenmusik** [comment]
should have same as prior functionality with Vive (where first controller is right hand and second controller is left)

**Comment by machenmusik** [comment]
@fernandojsg happily this appears to work with both latest 0.3.2 you have in master and also #163

**Comment by machenmusik** [comment]
@fernandojsg thanks for merging #163 -- rebuilt this on top, so you should be able to merge directly

**Comment by machenmusik** [comment]
@fernandojsg in thinking about it, the presence of the build.js file might get in the way of merge if you're going to rebuild, let me know if you'd like me to remove that file from the changeset

**Comment by fernandojsg** [comment]
I believe it will be better if we add fully oculus touch support: including a modified oculus touch model instead of the vive controller, tooltip position, offset to paint, and do the proper mapping.
What do you think @dmarcos @feiss ?

**Comment by machenmusik** [comment]
touch controllers are readily identifiable with tojiro's chromium but not sure if so w.r.t. openvr in nightly... should we make them work at all in chromium first, and see how much complaint there is out there before customizing?  biggest (only?) functional issue is thumbstick recentering making it hard to select brush size

**Comment by machenmusik** [comment]
so if we let the model come from `vive-controls` or `oculus-touch-controls` as dependencies of `paint-controls` instead of using `tracked-controls`, that would seem fine but agree with @fernandojsg that we may still need >tooltip position, offset to paint, and do the proper mapping
IMO, > biggest (only?) functional issue is thumbstick recentering making it hard to select brush size

**Comment by feiss** [comment]
Regarding thmbstick: Touchpad gesture for brush size should be relative #180

**Comment by fernandojsg** [comment]
Closed by https://github.com/aframevr/a-painter/pull/194

**Pull request closed without merging**
