### PR TITLE
UI tweaks

### PR DESCRIPTION
**Pull request by SamiraAtMicrosoft**
- lengthen ray casting distance for windows motion controllers
- hide tooltips upon open of UI menu
- add utility function to retrieve tooltips

### CODE REVIEW

**Comment by fernandojsg** [comment]
@SamiraAtMicrosoft looking nice!
I've just two comments:
- I would just hide the `tooltips` on the hand that has opened the menu. So even if I keep the panel open in one hand, I still could see the other hand tooltips to learn how the controller works.
- Once you close the menu, restore the tooltips visibility if still didn't hit the three times condition (system.numberStrokes === 3), so if you just clicked the button accidentally at the beginning you could still keep learning the position after it.

Feel free to include these changes or If you feel so I could just merge it right now and I could fix these after it, no problem from my side ;)

Thanks!!

**Comment by fernandojsg** [comment]
I'm thinking if it could be a better idea to fade out the opacity to something like 0.2-0.5 for the controller that has the ray instead of completely hide it

**Comment by SamiraAtMicrosoft** [comment]
Thanks @fernandojsg 
Great feedback!
I have made one more update which reduces the tooltip fade out duration to 1s as we discussed.
Regarding your feedback - I have actually hidden the `tooltips` on the hand that displays the ray line as this conflicts visually with the tooltip lines. Feel free to try this and let me know what you think.
I have incorporated your suggestion of restoring the tooltip visibility upon close of the menu.

**Comment by fernandojsg** [comment]
It works great 👍 thank you!

**Pull request merged**
