### PR TITLE
Fix OrbitControls

### PR DESCRIPTION
**Pull request by msub2**
OrbitControls causes multiple issues with camera rotation/control.
On the regular start page it forces the camera into the ground.
On loaded art pages there is strange rotation behavior, the camera goes askew very easily and makes it difficult to navigate.
wasd-controls and look-controls seem more than adequete on their own.

### CODE REVIEW

**Comment by dmarcos** [comment]
Looking at pieces using orbit-controls is a much better experience. We can use a [camera rig](https://aframe.io/docs/1.3.0/components/camera.html#sidebar) or disable wasd-controls / look-controls when in 2D mode.

**Comment by msub2** [comment]
Hmm, I'll try to see if I can get to behave better, but it wasn't behaving how I expected regular three.js OrbitControls to when I was testing

**Comment by dmarcos** [comment]
Any success with this? I see this PR has now conflicts. It needs a rebase

**Comment by msub2** [comment]
Been a bit busy, but will be looking at this more tonight now that almost everything else is out of the way.

**Comment by msub2** [comment]
After *lots* of trial and error I decided to try out the supermedium aframe-orbit-controls component and *finally* I got OrbitControls working the way I expected it to. I'm still removing the old orbit controls files, but now we have a working replacement.

**Comment by dmarcos** [comment]
Thanks!

**Pull request merged**
